### ISSUE TITLE
[download] Original file name is lost when downloading from browser

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-external-storage#11]
Currently, when users download a file uploaded via LFS the original file name is not suggested when the "Save as" dialogue appears; Instead, the OID is used. 

This is because we redirect the user to the storage URL which ends in the file's OID (SHA256).

**Comment by shevron** [comment]
LFS itself does not define a way to set the file name, or add extra parameters that allow the backend to set the file names (LFS's design assumes the client knows what the file name should be). 

I see a few ways to approach this, and we should do some thinking about the best approach:

## Client-based approach 
Follow the LFS approach that the "client knows", and use the relatively new `download="filename.bar"` HTML attribute in download links; This will require doing some extra work to override the HTML of template blocks that contain links, and the link displayed in the HTML will need to be a direct link to the storage backend, because `download="..."` behavior is not preserved following a redirect (I checked...). This in itself has some advantages (we will not need to override the resource download route / blueprint, thus allowing better fallback behavior), but also the downside that pre-signed download URLs may expire if the HTML page stays open. 

This can also be worked around by checking, and refreshing, the pre-signed URL when the link is clicked. 

Note that `download="..."` works in all modern browsers, but not in IE. 

## LFS Protocol Extension
Extend the LFS protocol with some custom attributes, at upload or at download, that allow setting a "content-disposition" header in pre-signed URLs for storage vendors that support it (Azure and S3 do). 

Pros: less client-side trickery, behavior is consistent across clients. 

Cons: Non-standard LFS features (Also not likely to be a part of the stasndard in the future). Will not be supported by all storage back-ends (e.g. local).

**Comment by rufuspollock** [comment]
@shevron good analysis. Options as i understand it:

* set a header / meta field in e.g. Azure or S3 storage that determines the download file name. This sets it in one place ... however it is has problem of somewhat violating content based addressing.
* download attribute - mostly supported now https://caniuse.com/#feat=download - but does mean you have to set this in places in the frontend

My slight preference is for 2nd option i think but i might need to think a bit more. (I feel that most others clients can take care of renaming e.g. via datapackage.json)

**Comment by shevron** [comment]
It is true that this is mostly a browser problem. The LFS assumption that the client should know the file name is generally correct, and even with a browser this can be done via the `download` attribute or some JS hacking. 

My inclination is also towards the 2nd option - there aren't that many places in the CKAN frontend to handle and it can be done via a JS module that will "hijack" clicks on `<a href>` tags with a custom handler. This will gracefully degrade to fetching the right file but with the wrong name, which I think is pretty OK. This approach can be done with minimal template overrides.

**Comment by shevron** [comment]
BTW, both Azure and S3 support setting the content-disposition header (header that specifies the file name when downloaded) when the file is fetched - not just when it is saved. This means that if we wanted to, we can customize download URLs on the LFS server level or on ckanext-external-storage without violating content based addressing. However, it will mean either extending the LFS protocol in a non-standard way (CKAN will have to send the filename when requesting a download URL), or alternatively it can be set by CKAN after the URL was generated (at least for Azure this is possible), but this means that ckanext-extenral-storage will have to be storage backend aware which kind of kills the whole abstraction that is Git LFS.

**Comment by shevron** [comment]
Unfortunately, it seems that at least Firefox will no longer respect the value of the `download="..."` attribute if it violates the same origin policy (which it usually does in our case). So looks like relying on `download` attribute functionality will not work (I've tested this and indeed it does not work). 

We are left with:
* LFS protocol extension as suggested above
* What I'd call a server side "leaky abstraction" approach to adding vendor-specific content-disposition parameters to generated download URLs; I will describe this option soon.

**Comment by shevron** [comment]
Suggested solution:

## CKAN Server Side URL mangling approach

In this approach, we do not modify Giftless or extend the LFS protocol, but add a feature in `ckanext-external-storage` that adds a vendor-specific query parameter to generated URLs to set the `content-disposition` header before redirecting the client to that URL. 

This can *only* work if vendors allow to set that query parameter without signing it (if it requires signing, we will have no choice but to do it in Giftless, which will require LFS protocol changes). 

This can be in the form of a config option, for example:
```
ckanext.external_storage.append_resource_download_query_params = 'ResponseContentDisposition=attachment; filename="{url}"'
```

This is somewhat of a leaky abstraction, as it requires the person configuring CKAN to be aware of the specifics of the storage backend vendor; The mere existence of this option is a bit of a hack and feels like a violation of proper encapsulation best practices - however, at least there is no vendor specific code anywhere, and no changes to LFS / Giftless that violate the protocol. 

Again, not sure if this can work - I need to further test this solution.

**Comment by shevron** [comment]
Ok, no dice; My last suggestion will not work for S3, which means we shouldn't do it.
