### ISSUE TITLE
Get tests passing

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-external-storage#19]
@shevron the tests are failing ... any ideas why and please can we get them passing 😄

**Comment by shevron** [comment]
Tests are failing for now only on CKAN 2.9 / master, not on CKAN 2.8.
Incidentally, they started failing after you merged #17 😜 (TBH I think it's a coincidence)

**Comment by shevron** [comment]
Looks like CKAN master now requires a newer version of Postgres with support for `JSONB` type. This is most likely fixable by ensuring the tests against CKAN master run with a newer version of pgsql. The min / max version of psql required for CKAN 2.9 is not well documented, but looks like 12.x *is* supported (not so for 2.8), see https://github.com/ckan/ckan/issues/5458
