### ISSUE TITLE
Integrate ckan3-js-sdk into extension

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-external-storage#3]
Integrate the standalone JS SDK into the extension in a clean way, using modern JS / ES build tools. 

## Acceptance Criteria
* [x] `ckan3-js-sdk` is specified in `package.json` and can be installed by running `npm install`
* [x] Running `npm build` or a similar command will generate a bundle JS file in `ckanext/external_storage/fanstatic/js/index.js` (or similar) which will include all the required, transpiled ES code in a single bundle
* [x] This file can be included in templates using `{% resource() %}` and defines a CKAN JS module using `ckan3-js-sdk` API
* [x] Add a `Makefile` target to wrap the NPM build command and help automate the process

## Technical Tasks
* [x] Set up `package.json` with the right dependencies + commands
* [x] Set up Webpack / Babel config files to generate the bundle
* [x] Create a wrapper script defining CKAN JS module
* [x] Add `Makefile` target to automate the build process

## References
See https://github.com/datopian/ckanext-querytool for an example of a CKAN extension with a modern JS environment

**Comment by mariorodeghiero** [comment]
@shevron I think everything here is done?!
