### ISSUE TITLE
Implement resource upload flow

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-external-storage#4]
## Acceptance Criteria

* [ ] When a file is uploaded for a resource, the file is saved via Git LFS to storage and the resource metadata is saved correctly in CKAN DB
* [ ] When a resource is an external URL normal CKAN behavior is maintained
* [ ] This is tested and works in all the following cases:
  * [ ] Add single resource to new dataset
  * [ ] Add multiple resources to a new dataset
  * [ ] Add single / multiple resources to an existing dataset
  * [ ] Replace a file in an existing resource (edit) 

## Technical Tasks
The following should happen in a single template (prob. `templates/external_storage/snippets/resource_upload.html` included from other templates):

* [x] When user selects a file, the file's hash is calculated (this can also be done when "Save" is clicked but would be nice to start early)
* [x] When user clicks "Save" or "Save and Add Another": 
  * [x] Calculate file hash if not already done
  * [x] Get an authz token (or verify we have one cached) (set the right scope)
  * [x] Send batch API upload request to LFS server
  * [x] Perform the upload + show progress bar
  * [x] Verify Upload
  * [x] Store file metadata in resource object - this must include the original file name, oid / sha256, and file size (needed to later download from LFS)
  * [x] Post resource form 
* [x] Continue normal CKAN flow - e.g. redirect to resource / dataset page

**Comment by mariorodeghiero** [comment]
@shevron implemented a progress bar [a12dd4c](https://github.com/datopian/ckanext-external-storage/commit/a12dd4c53d96cfd612d0b03bf9acf132b6f7090a)
