### ISSUE TITLE
Implement resource download flow

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-external-storage#5]
Implement the resource download flow for resources uploaded to external storage. Most likely should be based on a route that gets a signed URL from LFS on the server side and redirects the user to it. 

## Acceptance Criteria:
* [x] Resources uploaded to external storage via LFS are accessible to download from all CKAN UI links
* [ ] Resources uploaded to previous storage model are still accessible to download
* [ ] External URL resources are still accessible
* [ ] Users without full read access or `:data` subscope read access to the resource cannot download the resource

## Technical Tasks
* [x] Register a CKAN blueprint to override the download route
* [x] Blueprint should check for the `lfs_prefix` resource extra attribute and if not set, fall back to CKAN's default behavior (or cloudstorage's behavior if it is installed)
* [x] If it is an LFS managed file:
  * [x] Get an authz token by internally calling `authz_authorize` action
  * [x] Call Giftless from Python and check the response
  * [x] Redirect the user to the pre-signed download URL provided by Giftless
* [x] Even better: that logic should be encapsulated in an action; This allows using the API to get the download URL

## Open Questions
* We cannot maintain headers when redirecting (e.g. if LFS provides `header: { Authorization: ... }`). Should we rely on URLs including everything that the client needs in order to download?
* How do we fall back to legacy download methods?

**Comment by mariorodeghiero** [comment]
@shevron  
- Related the blueprint task - I would like to sync and do a pair programming 
   **Initiative:** I already bought a course about "REST APIs with Python and Flask" to learn more about these technologies.

Questions:
- Does the authz token needs to be a new request or can we use the old token?
- Is there another URL to get the assigned URL for download? if yes, what method?
